{
 "title": "HTTP Server Projeto",
 "tags": [ "projeto" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Go Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"http-server-projeto\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"http-server-projeto\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"http-server-projeto\"}[1m])",
     "legendFormat": "{{method}} {{endpoint}} {{status}}"
    }
   ]
  },
  {
   "title": "Total Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"http-server-projeto\"}[5m]))",
     "legendFormat": "Requests (5m window)"
    }
   ]
  }
 ]
}